### ISSUE TITLE
Feature request: RSS feed

### ISSUE THREAD

**Issue by gabrielkulp** [bleedingedgeai/bleedingedge.ai#13]
I tried appending `/feed`, `/feed.xml`, `/rss`, and `/rss.xml` to the base URL and then took a look in this repo and I don't see an RSS feed anywhere. If I'm mistaken, then interpret this as a request to make the feed link more discoverable :)

**Comment by brotzky** [comment]
hey, there is a feed!
https://bleedingedge.ai/rss/feed.xml and https://bleedingedge.ai/rss/feed.json

Is it more standard having it at the root? Any suggestions on how to make it more discoverable?

**Comment by gabrielkulp** [comment]
Awesome, thanks! Added to my reader!

I don't know about standard, but that's what I've seen before. At this point I wouldn't move it (could add a second path though) since that would cause problems for everyone who's subscribed.

I think the easiest solution is to add a link called "RSS", maybe in the footer near "About".

**Comment by brotzky** [comment]
Amazing, thanks, @gabrielkulp. Appreciate the feedback.
