### ISSUE TITLE
Missing important entry

### ISSUE THREAD

**Issue by gustheman** [bleedingedgeai/bleedingedge.ai#3]
This research on Matrix Multiplication from DeepMind is very important: https://www.deepmind.com/blog/discovering-novel-algorithms-with-alphatensor

this potentially can impact the whole ML field making it faster with better matrix multiplication algorithms and those were discovered by ML Agents

**Comment by LachyGroom** [comment]
Thank you! Any suggested title and description?

**Comment by gustheman** [comment]
"DeepMind improves matrix multiplication algorithms with AlphaTensor" 

"Based on their previous work with AphaZero, Deepmind managed to extend it to mathematics and unlock new possibilities for research"
