### ISSUE TITLE
Small font sizes

### ISSUE THREAD

**Issue by MaggieAppleton** [bleedingedgeai/bleedingedge.ai#5]
The font sizes are uncomfortably small to read on desktop. 16-20px is a comfortable desktop reading size for most people. Looks like most of the text is current 14px for article headlines, 13px for descriptions and 9px for metadata like dates.

Trying bumping that up to 16px for article headlines, 14px for descriptions, and 12px for metadata. It'll still feel quite compact, but at a size that's easier to read.

**Comment by brotzky** [comment]
Thanks for much for bringing that up, @MaggieAppleton. Internally, there have been a lot of discussions about font size so your input is highly appreciated. We'll make a full review as there are some bigger changes coming soon!

**Comment by MaggieAppleton** [comment]
Great to hear, Thanks! Love the project too. Very helpful given the pace of change 😅

**Comment by brotzky** [comment]
The font sizes are larger now (and even larger on extra wide screens)! Let us know what you think.

**Comment by brotzky** [comment]
Will close for now but feel free to chime in again if you like!
